artifact_uri: runs\mlflow/1/7730327f3cd24271928cba9569934fe9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 7730327f3cd24271928cba9569934fe9
run_name: train3
run_uuid: 7730327f3cd24271928cba9569934fe9
source_name: ''
source_type: 4
source_version: ''
start_time: 1714474270670
status: 1
tags: []
user_id: JOAOBO
