artifact_uri: runs\mlflow/1/efc234bf40f149f5ab39fad523cbb63c/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: efc234bf40f149f5ab39fad523cbb63c
run_name: train6
run_uuid: efc234bf40f149f5ab39fad523cbb63c
source_name: ''
source_type: 4
source_version: ''
start_time: 1714394043590
status: 1
tags: []
user_id: JOAOBO
