artifact_uri: runs\mlflow/1/7f3874a65c1745c99d990984cde56e9e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 7f3874a65c1745c99d990984cde56e9e
run_name: train2
run_uuid: 7f3874a65c1745c99d990984cde56e9e
source_name: ''
source_type: 4
source_version: ''
start_time: 1714473925235
status: 1
tags: []
user_id: JOAOBO
