artifact_uri: runs\mlflow/1/a4d1ac701d874fdcb140717bbd177a8e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: a4d1ac701d874fdcb140717bbd177a8e
run_name: train4
run_uuid: a4d1ac701d874fdcb140717bbd177a8e
source_name: ''
source_type: 4
source_version: ''
start_time: 1714501684197
status: 1
tags: []
user_id: JOAOBO
